### ISSUE TITLE
How to customize FFT size?

### ISSUE THREAD

**Issue by ardiantovn** [preiter93/ndrustfft#10]
Hi, I read in the docs that the fft output size will be (n/2) + 1. I want to customize the output size such as FFT_SIZE = 8 or 16 or 32. 
In [rustfft](https://github.com/ejmahler/RustFFT) library, it is possible to perform `planner.plan_fft_forward(FFT_SIZE)`. Is it possible to do that using ndrustfft library?
Thank you

**Comment by preiter93** [comment]
Hey @ardiantovn,
`
let handler: FftHandler<f64> = FftHandler::new(FFT_SIZE); 
`
calls `planner.plan_fft_forward(n)` under the hood, is this what you want?

The doc was actually wrong, an FftHandler, the output size will be *n* not *(n/2)+1* - *(n/2)+1* is the output size for the R2c transform. Corrected it [here](https://github.com/preiter93/ndrustfft/commit/af05679cb29ed496a37747e616674f170bc48d84).
Also added a simples [fft1 example](https://github.com/preiter93/ndrustfft/commit/6cd5b808826c9c30bd1d95063bc2b4c72adc1376).
