### ISSUE TITLE
Generalizing to other ndimensional array types?

### ISSUE THREAD

**Issue by skewballfox** [preiter93/ndrustfft#11]
Odd question? would you be open to generalizing this library from being strictly for ndarray? Essentially doing something similar to how burn handles supporting multiple tensor implementations using traits. 

Rustfft could stick to supporting ndarray (if desired), but could export the trait so that it could be implemented for other types.

I'm willing to try to implement this myself, I'm more wondering if this would likely get merged if I did.

**Comment by preiter93** [comment]
I dont plan anything like that to do.

IMO, what would be better for the rust ecosystem would be to provide an efficient multidimensional transform on slices &[T]. Storage containers like ndarray or nalgebra usually provide a way to get a slice cheaply (as_slice)

I tried that by iterating over chunks and using https://github.com/preiter93/transpose for transpose operations, but I couldn't get it to be good enough for parallel operations, so I stopped there. I personally don't have much motivation to push this topic anymore. Not to say I dont accept PRs in this direction. I think this crate would be a good place for ndim ffts considering its name.
