### ISSUE TITLE
N-dimensional FFT

### ISSUE THREAD

**Issue by timmyL17** [preiter93/ndrustfft#2]
Hi,

Are there any plans for this crate to support a full n-dimensional fft (e.g., in 2d, take fft along one direction, then transpose and take fft along second dimension, then transpose back)? It would be great to have functionality similar to the ofuton crate, but with real-to-complex, and using newer versions of rustfft.

**Comment by preiter93** [comment]
Hi,

the crate supports multi-dimensional transforms, say for 2d, you can first transform over axis=1, then over axis=0. Hope this is what you meant.
I think that is similar to what other libraries, such as matlab or numpy, do, i.e. they compute fft(fft(x,axis=1),axis=0).

I have added two examples to examples/fft2.rs and examples/rfft2.rs, hope this helps!

**Comment by timmyL17** [comment]
Thank you, that is what I need to do. I guess I was wondering if having a dedicated function would be more efficient, by shuffling axes of the output array instead of using a temporary. But I'll do it the straightforward way first before worrying about optimization. The examples help a lot with this.

**Comment by preiter93** [comment]
Yes, just let me know when you found a more performant way, then we can add a dedicated function for that! Maybe I will have a look how other libraries implement it
