### ISSUE TITLE
Incorrect result with 3-dimensional iFFT

### ISSUE THREAD

**Issue by shssoichiro** [preiter93/ndrustfft#3]
Hi, this is probably not a bug in this library but rather something I'm doing wrong. I'm writing a feature that requres a 3-D forward and inverse transform. The forward transform is producing correct values, but the inverse transform severely mismatches what I'm expecting. The code I'm using is below:

```rust
const SB_SIZE: usize = 16;
const TB_SIZE: usize = 3;
const BLOCK_AREA: usize = SB_SIZE * SB_SIZE;
const BLOCK_VOLUME: usize = BLOCK_AREA * TB_SIZE;
const COMPLEX_COUNT: usize = (SB_SIZE / 2 + 1) * SB_SIZE * TB_SIZE;

// Earlier in `self` initialization
self.ft = (
  FftHandler::new(TB_SIZE),
  FftHandler::new(SB_SIZE),
  R2cFftHandler::new(SB_SIZE),
);

// Applies a real-to-complex 3-dimensional FFT to `real`
fn real_to_complex_3d(
  &mut self, real: &[f32; BLOCK_VOLUME],
  output: &mut [Complex<f32>; COMPLEX_COUNT],
) {
  let input =
    ArrayView3::from_shape((TB_SIZE, SB_SIZE, SB_SIZE), real).unwrap();
  let mut temp2 = Array3::zeros((TB_SIZE, SB_SIZE, SB_SIZE / 2 + 1));
  let mut temp1 = Array3::zeros((TB_SIZE, SB_SIZE, SB_SIZE / 2 + 1));
  let mut output =
    ArrayViewMut3::from_shape((TB_SIZE, SB_SIZE, SB_SIZE / 2 + 1), output)
      .unwrap();

  ndfft_r2c(&input, &mut temp2, &mut self.ft.2, 2);
  ndfft(&temp2, &mut temp1, &mut self.ft.1, 1);
  ndfft(&temp1, &mut output, &mut self.ft.0, 0);
}

// Applies a complex-to-real 3-dimensional FFT to `complex`
fn complex_to_real_3d(
  &mut self, complex: &[Complex<f32>; COMPLEX_COUNT],
  output: &mut [f32; BLOCK_VOLUME],
) {
  let input =
    ArrayView3::from_shape((TB_SIZE, SB_SIZE, SB_SIZE / 2 + 1), complex)
      .unwrap();
  let mut temp0 = Array3::zeros((TB_SIZE, SB_SIZE, SB_SIZE / 2 + 1));
  let mut temp1 = Array3::zeros((TB_SIZE, SB_SIZE, SB_SIZE / 2 + 1));
  let mut output =
    ArrayViewMut3::from_shape((TB_SIZE, SB_SIZE, SB_SIZE), output).unwrap();

  ndifft(&input, &mut temp0, &mut self.ft.0, 0);
  ndifft(&temp0, &mut temp1, &mut self.ft.1, 1);
  ndifft_r2c(&temp1, &mut output, &mut self.ft.2, 2);
}
```

Could you provide some insight as to why the inverse FFT is not working correctly? And potentially, if this is something that seems like it might be a common pitfall, I think adding a 3D example to the `examples.rs` could be a great idea. Thanks!

**Comment by preiter93** [comment]
Hi,

sorry, I am away for travel for the next 3 weeks, without a laptop, otherwise I would look into it.

Could you try to make a self contained code in the spirit of the examples that I give? then assert (a) that the result after the inverse transform matches the original array and, optional, (b) compare it with the results from another library, maybe pythons numpy.fft.rfftn. in any case, I will look into it when I am back.

And thanks for raising the issue!

**Comment by shssoichiro** [comment]
Thanks! I copied what I had to a contrived example and it matched the output I manually copied from numpy. So I did some more debugging and it turns out that the program I'm porting from C to Rust does not get the same result that it puts in. So, that means I have more of a headache, but at least the issue is not in this library or how I'm using it. :slightly_smiling_face:
