### ISSUE TITLE
add the ability to optionally normalize

### ISSUE THREAD

**Issue by skewballfox** [preiter93/ndrustfft#4]
I'm currently trying to port a python library built on top of scipy/numpy, and the [dct function in scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.fftpack.dct.html), has an optional param norm, which when set to `"ortho"` seems to apply a scaling function depending on the transformation type. 

This can be applied after the transformation, I'm currently working on a closure to do so for dct2, but unless I'm misunderstanding what these functions are doing, it seems like its possible to apply this during the first pass through

**Comment by preiter93** [comment]
see the new branch  ``dct_ortho``.
I will eventually update the library on crates.io too

**Comment by preiter93** [comment]
Branch v0.4 has now the option to use custom normalizations.
There is also an example (fft_norm)
