### ISSUE TITLE
would STFT be in scope for this project

### ISSUE THREAD

**Issue by skewballfox** [preiter93/ndrustfft#6]
Hi, Currently I'm porting librosa's implementation of an [STFT](https://github.com/librosa/librosa/blob/c800e74f6a6ec5c27e0fa978d7355943cce04359/librosa/core/spectrum.py#L46) function to rust, though I wonder whether or not that would be something worth adding directly to this project. This is a branch of math I'm not too familiar with, so I'm not sure if it's *in scope* for what this library is meant to provide or if it's more of a thing meant to be built on top of this library

**Comment by preiter93** [comment]
Hey,  it doesnt quite fit the idea of this library which is to make multidimensional transforms easier by combining ndarray + rustfft/realfft/rustdct.

I think a stft could be its own crate (build on top of rustfft)

**Comment by skewballfox** [comment]
I have an stft implementation implemented in my crate. It's linked in the related [issue](https://github.com/secretsauceai/mfcc-rust/issues/27). It's only for arrays of 1 and 2 dims, currently has a hardset window function, and currently only accepts f32s, though all of those things can be iterativley improved.

I guess I'm wondering is this something that would actually be useful to people or would it take a tremendous amount of effort to iterate to the point that it benefits more than say 5 people solving the exact same problem? I don't have a signal processing background so I'm still unsure of the scope of the utility I guess
