### ISSUE TITLE
Support RustFft features

### ISSUE THREAD

**Issue by dancixx** [preiter93/ndrustfft#8]
Hi guys, 

is it possible to support RustFft included features like avx, sse and neon?

**Comment by preiter93** [comment]
Hey, 

yes, that makes sense. I added it in [PR](https://github.com/preiter93/ndrustfft/pull/9). It's released under v0.4.2.

The feature flags are all enabled by default to match rustffts default feature specs

**Comment by preiter93** [comment]
Added in v0.4.2
